name: prman
version: 0.1.0
summary: Command line tool for automatic GitLab PR creation.
description: Check out https://github.com/ilyalatt/prman.

grade: devel
confinement: classic # there is a problem with glibc in 'strict' confinement
base: core18

apps:
  prman:
    command: bash run.sh
    plugs:
      - home

parts:
  prman:
    plugin: dump
    source: bundle
